export const BookData=[
    {
      orderId: 0,
      id:0 ,
      book_title:' The Island Of Zanzibar',
      book_url:'https://i.pinimg.com/474x/4c/80/48/4c8048d18866811c4a24a015ed3347dc.jpg',
      author_name:'Willie Wild',
      genre:'Book',
      Available:'Out of Stock',
      price:'234'
    },
    {
      orderId: 1,
      id:1,
      book_title:'The Myth Of Mau',
      book_url:'https://i.pinimg.com/474x/4a/9e/cb/4a9ecb89fb2cea195c9cc048f05c914c.jpg',
      author_name:'John Nottingham',
      book_genre:'Story',
      Available:'Available',
      price:'3440',
    },
    {
      orderId: 2,
      id:2,
      book_title:'Camping In Kenya',
      book_genre: 'Book',
      Available:'Available',
      book_url:'https://i.pinimg.com/474x/ad/f9/98/adf9985afccb5f999c8084de4a81fd18.jpg',
      author_name:'John Arle',
      price:'350',
    },
    {
      orderId: 3,
      id:3,
      book_title:'Ancient Greece',
      book_genre: 'Myth',
      Available:'Available',
      book_url:'https://i.pinimg.com/474x/1e/1a/83/1e1a8322f25ad4a1897a78704b4298f1.jpg',
      author_name:'Ali A. Mazrui',
      price:'34500',
    },
    {
      orderId: 4,
      id:4,
      book_title:'Come Back Africa ',
      Available:'Out Of Stock',
      book_genre:'Story',
      book_url:'https://i.pinimg.com/474x/9a/5d/28/9a5d289b33c979f8638e3e86c172822f.jpg',
      author_name:'John Argle',
      price:'33450',
    },
    {
      orderId: 5,
      id:5,
      book_title:'Regional Integration',
      author_name:'Msuya Mangachi',
      Available:'',
      book_genre:'Book',
      price:'3750',
      book_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFZLMztkhFjw_bc5cyRQs_loJ4_DLkhYmWXpML-XwQ1A&s'},
    {
      orderId: 6,
      id:6,
      book_title:'Quest For Regional Integration',
      author_name:'S kai wajid',
      Available:'Few Unit Left',
      book_genre:'Poem',
      price:'34950',
      book_url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrI3catScbJ5UsW8aXiEkNU_mzKWQR6VrbIJeqxqwN9Q&s'},
    {
      orderId: 7,
      id:7,
      book_title:'The Karagwe Kingdom',
      author_name:'Israel K. Katoke',
      Available:'Few Unit Left',
      book_genre:'Poem',
      price:'4650',
      book_url:'https://i.pinimg.com/474x/fe/d7/ce/fed7ce521a29d95c5c58039d07993c3d.jpg'
    },
    {
      orderId: 8,
      id:8,
      book_title:'The ExploitationOf EA',
      author_name:'R.Coupland',
      Available:'Available',
      book_genre:'Novel',
      price:'7850',
      book_url:'https://i.pinimg.com/474x/a9/0a/a5/a90aa572bbe64a3ae497d710b4f9fbec.jpg'
    },
    {
      orderId: 9,
      id:9,
      book_title:'The Tanganyika Under German Rule',
      author_name:'John IIiffe',
      Available:'Outdated',
      book_genre:'Poem',
      price:'3450',
      book_url:'https://i.pinimg.com/474x/a2/5d/f4/a25df471f28dd6d102d6fd8eabc11057.jpg'
    },
    {
      orderId: 10,
      id:10,
      book_title:'The Guide To South And EA',
      author_name:'Kayle Katoke',
      book_genre:'Book',
      Available:'Few Units Left',
      price:'450',
      book_url:'https://i.pinimg.com/474x/f8/b7/e0/f8b7e0aacb7940737a8ceed932f9ad8c.jpg'
    }
]
    

